# Generated by Django 2.1.3 on 2018-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='date',
        ),
        migrations.AddField(
            model_name='ride',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
